name: Update Hosts File

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create file if missing
        run: |
          if [ ! -f hosts.txt ]; then
            touch hosts.txt
            echo "Initial empty file" > hosts.txt
          fi

      - name: Download hosts file
        run: curl -f -s -o hosts.tmp https://schakal.ru/hosts/hosts.txt && mv hosts.tmp hosts.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Проверяем изменения
          if [ -z "$(git status --porcelain hosts.txt)" ]; then
            echo "No changes detected"
          else
            git add hosts.txt
            git commit -m "Auto-update hosts file"
            git push
          fi
